### ISSUE TITLE
enable namespace setting in evals/benchmark tool

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIEval#120]
Not only support default namespace, but also support specified namespace.

If the workload is deployed in other namespace, it will meet with error:
```
Traceback (most recent call last):
[OPEA BENCHMARK] 🚀 Example: chatqna Service: chatqna-backend-server-svc, Running test...
  File "/home/sdp/validation-action-runner/_work/Validation/Validation/GenAIEval/evals/benchmark/benchmark.py", line 223, in <module>
    process_service(example, service_type, case_data, test_suite_config)
  File "/home/sdp/validation-action-runner/_work/Validation/Validation/GenAIEval/evals/benchmark/benchmark.py", line [17](https://github.com/opea-project/Validation/actions/runs/10768499945/job/29857837856#step:5:18)8, in process_service
    run_service_test(example, service_type, service, test_suite_config)
  File "/home/sdp/validation-action-runner/_work/Validation/Validation/GenAIEval/evals/benchmark/benchmark.py", line 149, in run_service_test
    svc_ip, port = get_service_ip(
  File "/home/sdp/validation-action-runner/_work/Validation/Validation/GenAIEval/evals/benchmark/benchmark.py", line 125, in get_service_ip
    svc_ip, port = get_service_cluster_ip(service_name)
  File "/home/sdp/validation-action-runner/_work/Validation/Validation/GenAIEval/evals/benchmark/utils.py", line 57, in get_service_cluster_ip
    raise ValueError(f"Service {service_name} not found.")
ValueError: Service chatqna-backend-server-svc not found.
```

**Comment by joshuayao** [comment]
Hi @daisy-ycguo. User-specific namespace is supported now(#160). Can I close this issue?

**Comment by joshuayao** [comment]
Close for no further request.
