### ISSUE TITLE
Failed to install dependencies of OPEA benchmark tool，Python version 3.9

### ISSUE THREAD

**Issue by feng-intel** [opea-project/GenAIEval#144]
Follow [ChatQnA/benchmark/performance#benchmark-with-docker](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/benchmark/performance#benchmark-with-docker),  runnig "python benchmark.py" needs k8s, and then the below installation is failed.
```

# pip install -r ../../requirements.txt

Collecting bigcode-eval@ git+https://github.com/bigcode-project/bigcode-evaluation-harness.git
  Cloning https://github.com/bigcode-project/bigcode-evaluation-harness.git to /tmp/pip-install-kg39b6qp/bigcode-eval_43d5357e6dd8402a84e4cc7db905d2de
  Running command git clone --filter=blob:none -q https://github.com/bigcode-project/bigcode-evaluation-harness.git /tmp/pip-install-kg39b6qp/bigcode-eval_43d5357e6dd8402a84e4cc7db905d2de
  Resolved https://github.com/bigcode-project/bigcode-evaluation-harness.git to commit 7c02b2f678791ad618ad069a4d21a1cb70915949
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kg39b6qp/bigcode-eval_43d5357e6dd8402a84e4cc7db905d2de/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kg39b6qp/bigcode-eval_43d5357e6dd8402a84e4cc7db905d2de/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e4fi__h1
       cwd: /tmp/pip-install-kg39b6qp/bigcode-eval_43d5357e6dd8402a84e4cc7db905d2de/
  Complete output (40 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-e4fi__h1/bigcode_eval.egg-info
  writing /tmp/pip-pip-egg-info-e4fi__h1/bigcode_eval.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-e4fi__h1/bigcode_eval.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-e4fi__h1/bigcode_eval.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-e4fi__h1/bigcode_eval.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-e4fi__h1/bigcode_eval.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-e4fi__h1/bigcode_eval.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-kg39b6qp/bigcode-eval_43d5357e6dd8402a84e4cc7db905d2de/setup.py", line 30, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
      return run_commands(dist)
    File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
      dist.run_commands()
    File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
      super().run_command(command)
    File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 311, in run
      self.find_sources()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
      mm.run()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 545, in run
      self.prune_file_list()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/sdist.py", line 161, in prune_file_list
      super().prune_file_list()
    File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
      base_dir = self.distribution.get_fullname()
    File "/usr/local/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
      return _distribution_fullname(self.get_name(), self.get_version())
    File "/usr/local/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
      canonicalize_version(version, strip_trailing_zero=False),
  TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
  ----------------------------------------
WARNING: Discarding git+https://github.com/bigcode-project/bigcode-evaluation-harness.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement bigcode-eval (unavailable) (from versions: none)
ERROR: No matching distribution found for bigcode-eval (unavailable)

```

**Comment by lkk12014402** [comment]
> ERROR: No matching distribution found for bigcode-eval (unavailable)

hi, @feng-intel I can't reproduce the issue with python 3.9

![image](https://github.com/user-attachments/assets/de63dd8d-2ed7-446e-902b-f1d478d85f38)
