### ISSUE TITLE
Missing dependencies in evals/benchmark/stresscli/requirements.txt

### ISSUE THREAD

**Issue by joshuayao** [opea-project/GenAIEval#97]
**Reproduce the issue:**
```shell
cd evals/benchmark/stresscli
pip install -r requirements.txt
./stresscli.py load-test --profile run.yaml
``` 

**Issue:**
Missing `sseclient`:

```shell
Traceback (most recent call last):
  File "/root/miniforge3/envs/opea-eval/bin/locust", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniforge3/envs/opea-eval/lib/python3.11/site-packages/locust/main.py", line 108, in main
    docstring, _user_classes, shape_classes = load_locustfile(_locustfile)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/opea-eval/lib/python3.11/site-packages/locust/util/load_locustfile.py", line 70, in load_locustfile
    loader.exec_module(imported)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/josh/GenAIEval/evals/benchmark/stresscli/locust/aistress.py", line 12, in <module>
    import sseclient
ModuleNotFoundError: No module named 'sseclient'
``` 

Missing `transformers` after installing sseclient:

```shell
Traceback (most recent call last):
  File "/root/miniforge3/envs/opea-eval/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/root/miniforge3/envs/opea-eval/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/root/miniforge3/envs/opea-eval/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/root/josh/GenAIEval/evals/benchmark/stresscli/locust/aistress.py", line 74, in bench_main
    reqData = bench_package.getReqData()
              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'getReqData'
```

**Comment by daniel-de-leon-user293** [comment]
Following up with the same issue. Was there a fix for this?

**Comment by yinghu5** [comment]
@joshuayao and All, 
Thank you a lot for report. the issue should be fixed now.  one can follow the steps in https://github.com/opea-project/GenAIEval/blob/main/README.md.  Close as completed.
